#!/usr/bin/python3
# My service for doing some basic network monitoring.

# Imports
import os
import sys
import json
import flask
import subprocess
import socket
import ipaddress
import time
import threading
from datetime import datetime
from mac_vendor_lookup import BaseMacLookup, MacLookup

# Enable import from the parent directory
pdir = os.path.dirname(os.path.dirname(os.path.realpath(__file__)))
if pdir not in sys.path:
    sys.path.append(pdir)

# Local imports
from lib.config import ConfigField
from lib.db import Database, DatabaseConfig
from lib.arp import Arp, ArpError
from lib.nmap import Nmap, NmapError
from lib.service import Service, ServiceConfig
from lib.oracle import Oracle
from lib.nla import NLAEndpoint, NLAEndpointInvokeParameters, NLAResult
from lib.cli import ServiceCLI

# Service imports
from device import KnownDeviceConfig, DeviceHardwareAddress, \
                   DeviceNetworkAddress, Device


# =============================== Config Class =============================== #
class WardenConfig(ServiceConfig):
    def __init__(self):
        """Constructor."""
        super().__init__()
        # create lumen-specific fields to append to the existing service fields
        fields = [
            ConfigField("known_devices",    [KnownDeviceConfig], required=True),
            ConfigField("refresh_rate",     [int],      required=False,     default=120),
            ConfigField("ping_timeout",     [float],    required=False,     default=0.25),
            ConfigField("ping_tries",       [int],      required=False,     default=1),
            ConfigField("sweep_threshold",  [int],      required=False,     default=3600),
            ConfigField("initial_sweeps",   [int],      required=False,     default=1),
            ConfigField("mac_vendor_cache_path", [str], required=False,     default=os.path.join(os.path.dirname(os.path.realpath(__file__)), ".mac_vendors.txt")),
            ConfigField("database",         [DatabaseConfig], required=False, default=DatabaseConfig.from_json({
                "path": os.path.join(os.path.dirname(os.path.realpath(__file__)), ".warden.db"),
                "check_same_thread": False,
                "timeout": 5.0,
                "busy_timeout_ms": 5000,
            })),
            ConfigField("device_ttl",       [int],      required=False,     default=604800),
        ]
        self.fields += fields


# ============================== Database Class ============================== #
class WardenDatabase(Database):
    """Owns all on-disk persistence for warden's device index.

    This is a THIN subclass of `lib.db.Database`: connection management, DDL,
    reads, the safe parameterized upsert and the parameterized delete all live
    in the parent. This class only supplies the `devices` schema and the
    `Device` (de)serialization, plus the resilience/thread-safety policy warden
    needs. Every row stores the full serialized `Device` in the built-in
    Uniserdes `encoded_obj` column, plus a few extra visible columns (macaddr
    [PRIMARY KEY], ipaddr, name, last_seen) for querying and debuggability. All
    SQL/DDL is generated by Uniserdes / the parent `Database` helpers — there
    is NO hand-written SQL in this class.

    The on-disk `.warden.db` is a fresh, rebuildable cache (warden re-indexes
    from network sweeps): there is NO schema migration or back-compat handling.

    Thread-safety: a downstream worker-thread pool issues device updates from
    threads OTHER than the one that created this object. The object opts into
    the parent's thread-safe connection mode (`check_same_thread=False` + a
    busy timeout) and serializes ALL access — including calls into inherited
    parent methods — through an internal lock, so the single shared connection
    is only ever touched by one thread at a time.

    Resilience: if the database cannot be opened or its table cannot be created
    (corrupt/unwritable file), the object degrades to a disabled,
    in-memory-only mode with an error-level log rather than crashing the
    service. Individual save/delete failures are also logged at error level
    (never silently swallowed) while keeping the in-memory hot path alive.
    """

    # default table name; kept identical to the original inline implementation
    DEFAULT_TABLE = "devices"
    # how long (ms) sqlite will wait on a locked DB before raising
    BUSY_TIMEOUT_MS = 5000
    # the extra (visible) columns stored alongside the built-in ``encoded_obj``
    # column, in on-disk order. ``macaddr`` is the PRIMARY KEY. All three of
    # macaddr/ipaddr/name are NESTED attributes on Device (device.hw_addr.macaddr,
    # device.net_addr.ipaddr, device.known_device.name) so they cannot be plain
    # visible fields — they are supplied via Uniserdes ``extra_fields``.
    # ``last_seen`` is top-level but is also kept as an extra for a simple,
    # consistent all-extras layout.
    EXTRA_COLUMNS = ("macaddr", "ipaddr", "name", "last_seen")
    # full column order (encoded_obj first, then the extras) — this MUST match
    # the tuple order produced by Device.to_sqlite3(..., extra_fields=...).
    COLUMNS = ("encoded_obj",) + EXTRA_COLUMNS

    def __init__(self, config: DatabaseConfig, log=None, table: str = None):
        """Constructor. Takes a `DatabaseConfig` (its `path` selects the on-disk
        file), an optional log (anything with a `write(msg)` method), and an
        optional table name override.
        """
        # THREAD-SAFETY GUARDRAIL: the downstream worker-thread pool shares this
        # single connection across threads, so the connection MUST be opened
        # cross-thread-safe regardless of what the YAML/config provided. A
        # hand-written config must not be able to silently break the worker pool,
        # so we enforce `check_same_thread=False` and ensure a busy timeout /
        # `timeout` is set (falling back to `BUSY_TIMEOUT_MS`). Overriding a
        # conflicting provided value is logged. The internal lock (below)
        # provides the serialization sqlite3 requires when a single connection
        # is shared across threads.
        self.log = log
        if getattr(config, "check_same_thread", True) is not False:
            self._log("[WARN] warden requires a cross-thread-safe DB "
                      "connection; overriding check_same_thread=%r -> False" %
                      getattr(config, "check_same_thread", True))
            config.check_same_thread = False
        if getattr(config, "busy_timeout_ms", None) is None:
            config.busy_timeout_ms = self.BUSY_TIMEOUT_MS
        if getattr(config, "timeout", None) is None:
            config.timeout = self.BUSY_TIMEOUT_MS / 1000.0
        super().__init__(config)
        self.path = config.path
        self.table = table if table is not None else self.DEFAULT_TABLE
        # a single lock serializes every connection touch so the shared
        # check_same_thread=False connection is only ever used by one thread at
        # a time
        self.lock = threading.Lock()
        # persistence is only considered enabled once init() succeeds; until
        # then (or after a fatal init failure) the object is a no-op mirror and
        # the service runs in-memory-only
        self.enabled = False

    # ------------------------------ Logging --------------------------------- #
    def _log(self, msg: str):
        """Writes an informational message to the log, if one is present."""
        if self.log is not None:
            self.log.write(msg)

    def _log_error(self, msg: str):
        """Writes an error-level message to the log (distinct from routine info
        logs) so sustained persistence failures are noticeable.
        """
        if self.log is not None:
            self.log.write("[ERROR] %s" % msg)

    # ------------------------- Schema helpers ------------------------------- #
    def _table_ddl(self) -> str:
        """Returns the Uniserdes-generated ``CREATE TABLE`` statement for the
        device table. The DDL is produced entirely by Uniserdes (no hand-written
        SQL): ``encoded_obj`` (built-in) followed by the extra columns, with
        ``macaddr`` as PRIMARY KEY. Type-representative placeholder values are
        passed so Uniserdes can infer each extra column's SQLite type.
        """
        return Device().get_sqlite3_table_definition(
            self.table,
            fields_to_keep_visible=[],
            extra_fields={"macaddr": "", "ipaddr": "", "name": "", "last_seen": 0},
            primary_key_field="macaddr",
            include_encoded_obj=True,
        )

    # --------------------------- Connection --------------------------------- #
    def _connect(self):
        """Returns the shared connection (opened cross-thread with a busy timeout
        by the parent). Caller MUST hold `self.lock`.
        """
        return self.get_connection()

    def close(self):
        """Closes the object's connection, if open."""
        with self.lock:
            self.close_connection()

    # ------------------------------ Lifecycle ------------------------------- #
    def init(self) -> bool:
        """Opens the database and creates the devices table if it does not already
        exist. On any failure (corrupt/unwritable/locked DB) the object degrades
        to in-memory-only mode with an error-level log rather than crashing.
        Returns True if persistence is enabled, False otherwise.

        `.warden.db` is a fresh, rebuildable cache (warden re-indexes from
        network sweeps): there is NO schema migration or back-compat handling.
        """
        try:
            with self.lock:
                # Create the table from the Uniserdes-generated DDL.
                self.execute(self._table_ddl(), do_commit=True)
            self.enabled = True
        except Exception as e:
            self.enabled = False
            self._log_error("Failed to initialize the device database at %s; "
                            "continuing in-memory-only: %s" % (self.path, e))
            # drop any half-open connection so we don't reuse a bad handle
            self.close()
        return self.enabled

    def load_all(self) -> dict:
        """Loads all persisted devices, returning a dict mapping lowercased macaddr
        to `Device`. Each device is reconstructed from its ``encoded_obj`` column
        via `Device.from_sqlite3()` (the extra columns are ignored on read). A
        corrupt/unreadable database or a row that fails to parse is logged and
        skipped rather than crashing startup.
        """
        devices = {}
        if not self.enabled:
            return devices
        try:
            with self.lock:
                # Reuse the parent's search(); if the table doesn't exist yet it
                # returns an empty list and there's nothing to load.
                rows = list(self.search(self.table, None))
        except Exception as e:
            self._log_error("Failed to read devices from the database: %s" % e)
            return devices

        # parse each row independently so one bad row doesn't sink the rest
        for row in rows:
            try:
                # Decode the whole device from the encoded_obj column (index 0);
                # trailing extra columns are ignored.
                device = Device.from_sqlite3(row, include_encoded_obj=True)
                mac = device.hw_addr.macaddr if device.hw_addr else None
                if mac is None:
                    # fall back to the visible macaddr column if present
                    mac = row[1] if len(row) > 1 else None
                if mac is None:
                    continue
                devices[mac.lower()] = device
            except Exception as e:
                self._log("Skipping unparseable device row: %s" % e)
                continue
        return devices

    def save(self, device: Device):
        """Upserts a single device. The full `Device` object is serialized to the
        built-in ``encoded_obj`` column; the nested macaddr/ipaddr/name and the
        top-level last_seen are stored as extra visible columns for
        queryability. All conversion and tuple building is done by Uniserdes;
        persistence uses the parent's parameterized upsert. Failures are logged
        at error level and swallowed so a persistence failure never takes down
        the in-memory hot path.
        """
        if not self.enabled:
            return
        # a device without a hardware address has no primary key; skip it
        if device.hw_addr is None or device.hw_addr.macaddr is None:
            return
        try:
            macaddr = device.hw_addr.macaddr.lower()
            ipaddr = device.net_addr.ipaddr if device.net_addr else None
            name = device.known_device.name if device.known_device else None
            last_seen = int(device.last_seen.timestamp()) if device.last_seen else None

            # Build the row entirely via Uniserdes: encoded_obj + extra columns,
            # in the same order as COLUMNS. No hand-written SQL.
            row = device.to_sqlite3(
                fields_to_keep_visible=[],
                extra_fields={
                    "macaddr": macaddr,
                    "ipaddr": ipaddr,
                    "name": name,
                    "last_seen": last_seen,
                },
                include_encoded_obj=True,
            )

            with self.lock:
                # Reuse the parent's SAFE, parameterized upsert (values bound via
                # ? placeholders).
                self.insert_or_replace(self.table, row, columns=self.COLUMNS)
        except Exception as e:
            self._log_error("Failed to save device to the database: %s" % e)

    def delete(self, macaddr: str):
        """Removes a single device (by MAC address). Uses the parent's general,
        parameterized key-delete helper (no raw SQL in warden). Failures are
        logged at error level and swallowed.
        """
        if not self.enabled:
            return
        try:
            with self.lock:
                # Reuse the parent's general parameterized key-delete helper.
                self.delete_by_column(self.table, "macaddr", macaddr.lower())
        except Exception as e:
            self._log_error("Failed to delete device from the database: %s" % e)


# ============================== Service Class =============================== #
class WardenService(Service):
    def __init__(self, config_path):
        """Constructor."""
        super().__init__(config_path)
        self.config = WardenConfig()
        self.config.parse_file(config_path)

        # make a few config assertions
        assert self.config.refresh_rate > 0, "the refresh rate must be greater than 0"
        assert self.config.ping_timeout > 0.0, "the ping timeout must be greater than 0"
        assert self.config.ping_tries > 0, "the ping try count must be greater than 0"
        assert self.config.device_ttl > 0, "the device TTL must be greater than 0"

        # the service will keep a cache of IP/MAC addresses, but it starts as an
        # empty dictionary
        self.cache = {}
        self.last_sweep = datetime.fromtimestamp(0)

        # set up the on-disk device database (a durable mirror of the in-memory
        # cache). All persistence logic lives in `WardenDatabase`, which owns
        # its own thread-safe connection and degrades gracefully on failure.
        self.db = WardenDatabase(self.config.database, log=self.log)

        # instantiate the low-level `arp` and `nmap` command-line wrappers once
        # and reuse them for every lookup/ping (see `self.arp`/`self.ping_nmap`)
        self.arp_client = Arp()
        self.nmap_client = Nmap()


    def run(self):
        """Overridden main function implementation."""
        super().run()

        def can_sweep():
            """Helper function to determine if it's time for a sweep."""
            time_to_sweep_threshold = now.timestamp() - self.last_sweep.timestamp()
            can_sweep = time_to_sweep_threshold >= self.config.sweep_threshold
            return can_sweep

        # get our own IP address
        self.addr = self.get_address()
        self.log.write("Warden's IP address: %s" % self.addr)

        # initialize the on-disk device database and load any previously-cached
        # devices so the index survives a reboot
        self.db.init()
        loaded = self.db.load_all()
        for macaddr in loaded:
            self.cache[macaddr] = loaded[macaddr]
        self.log.write("Loaded %d device(s) from the database." % len(loaded))

        # before entering the main loop, we'll sweep the network a number of
        # times to build up the cache of connected devices
        for i in range(self.config.initial_sweeps):
            self.log.write("Performing initial network sweep (%d/%d)" %
                           ((i + 1), self.config.initial_sweeps))
            self.sweep()

        # dump out the current state of the cache
        self.log.write("Initial cache entries:")
        for entry in self.cache:
            self.log.write(" - %s" % self.cache[entry].to_str_brief())

        # loop forever
        while True:
            now = datetime.now()
            pfx = "[%s]" % now.strftime("%Y-%m-%d %H:%M:%S")

            # if we're past the sweep threshold, sweep the network
            if can_sweep():
                # before sweeping, update the MAC address vendor cache
                self.log.write("%s Refreshing MAC address vendor cache..." % pfx)
                self.mac_vendor_refresh_cache()

                # initiate the sweep, then write out all entries in the cache
                self.log.write("%s Sweeping the network..." % pfx)
                self.sweep()
                for entry in self.cache:
                    self.log.write(" - %s" % self.cache[entry].to_str_brief())

            # iterate across all devices stored in the cache
            for addr in self.cache:
                device = self.cache[addr]

                # ping the device and update if it responds
                ping_tries = self.config.ping_tries * 2
                if self.ping(device.net_addr.ipaddr, tries=ping_tries):
                    self.log.write("%s Device \"%s\" is responding." %
                                   (pfx, device.to_str_brief()))
                    device.set_last_seen(datetime.now())
                    # persist the updated last_seen to the durable DB mirror
                    self.db.save(device)

            # prune any devices that haven't been seen within the configured TTL
            # from both the cache and the database
            self.prune_stale_devices(now=datetime.now())

            # sleep for the specified amount of seconds
            time.sleep(self.config.refresh_rate)


    # ------------------------------- Caching -------------------------------- #
    def cache_get(self, macaddr: str):
        """Returns the matching device object, or None."""
        macaddr = macaddr.lower()
        return None if macaddr not in self.cache else self.cache[macaddr]

    def cache_set(self, device: Device):
        """Takes a MAC address and adds an entry to the cache. The `Device` object is
        returned. The device is also upserted to the on-disk database so the
        cache survives a reboot.
        """
        macaddr = device.hw_addr.macaddr.lower()
        self.cache[macaddr] = device
        self.db.save(device)
        return device

    # ------------------------------ Database -------------------------------- #
    def prune_stale_devices(self, now: datetime = None):
        """Removes any device whose `last_seen` is older than `device_ttl` seconds
        from both the in-memory cache and the database. Returns the list of
        pruned MAC addresses.
        """
        now = datetime.now() if now is None else now
        cutoff = now.timestamp() - self.config.device_ttl

        # identify stale devices first (don't mutate the dict while iterating)
        stale = []
        for macaddr in self.cache:
            device = self.cache[macaddr]
            # a device with no last_seen has never been observed; treat as stale
            last_seen_ts = device.last_seen.timestamp() if device.last_seen else 0
            if last_seen_ts < cutoff:
                stale.append(macaddr)

        # remove stale devices from cache and DB
        for macaddr in stale:
            self.log.write("Pruning stale device: %s" %
                           self.cache[macaddr].to_str_brief())
            del self.cache[macaddr]
            self.db.delete(macaddr)
        return stale

    # --------------------------------- API ---------------------------------- #
    def get_address(self):
        """Attempts to determine (and return) the IP address of the service."""
        sock = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)
        sock.settimeout(0)
        addr = None
        try:
            # connect to some arbitrary address
            sock.connect(("192.168.0.1", 1))
            addr = sock.getsockname()[0]
        except:
            addr = "192.168.0.100"

        # close the socket and return the address
        sock.close()
        return addr

    def get_netmask(self):
        """Gets the service's IP address with the "/24" netmask included at the end."""
        args = ["ip", "-o", "-f", "inet", "addr", "show"]
        result = subprocess.run(args, capture_output=True)
        assert len(result.stderr) == 0, "\"ip\" command produced error messages"

        # parse the output, line-by-line, for the correct value
        addr = self.get_address()
        for line in result.stdout.decode().split("\n"):
            # remove extra whitespace and skip empty lines
            line = line.strip()
            if len(line) == 0:
                continue

            # split into pieces and skip lines that don't have enough
            pieces = line.split()
            if len(pieces) < 4:
                continue

            # extract the net mask and compare against our address
            mask = pieces[3]
            if addr in mask:
                return mask

        # we shouldn't reach here...
        assert False, "failed to look up netmask"

    def get_all_addresses(self):
        """Returns a list of all the valid addresses on the same network as the
        service.
        """
        network = ipaddress.IPv4Network(self.get_netmask(), strict=False)
        result = []
        for addr in list(network.hosts()):
            result.append(str(addr))
        return result

    def sweep(self):
        """Sweeps the entire range of IP addresses in the same subnet as the
        service's IP address. Returns dictionary of IP addresses and MAC
        addresses corresponding to the devices that responded.
        """
        self.last_sweep = datetime.now()
        # get all addresses, and our own address
        addr = self.get_address()
        addresses = self.get_all_addresses()

        # ping all addresses
        devices_found = []
        log_msg = "Trying address %s"
        for (i, addr) in enumerate(addresses):
            # write a message to the log
            log_msg_end = "" if i < len(addresses) - 1 else "\n"
            self.log.write(log_msg % addr, begin="\r", end=log_msg_end)

            d = Device()
            d.init_defaults()

            # ping and save the address if the ping succeeded
            if self.ping(addr):
                d.set_network_address(DeviceNetworkAddress.from_json({
                    "ipaddr": addr,
                }))
                self.log.write(" - UP", show_prefix=False, end="")
            else:
                continue

            # perform an ARP lookup to get the device's MAC address. If we can't
            # get the MAC address, skip it
            macaddr = self.arp(addr, do_ping=False)
            if not macaddr:
                continue

            macaddr = macaddr.lower()
            self.log.write(" - macaddr=\"%s\"" % macaddr, show_prefix=False, end="")

            # look up the vendor for this MAC address
            vendor = None
            try:
                vendor = self.mac_vendor(macaddr)
                self.log.write(" - vendor=\"%s\"" % vendor, show_prefix=False, end="")
            except Exception as e:
                pass

            # save the MAC addr and vendor information to the device object
            d.set_hardware_address(DeviceHardwareAddress.from_json({
                "macaddr": macaddr,
                "vendor": vendor,
            }))

            # does this MAC address match any of our known devices? If so,
            # set the device object's known device to point at the known
            # device's info object
            for known_dev in self.config.known_devices:
                for known_mac in known_dev.macaddrs:
                    if known_mac.lower() == macaddr:
                        d.set_known_device(known_dev.copy())
                        break

            # store what information we collected on this device in the cache
            d.set_last_seen(datetime.now())
            self.cache_set(d)

            # append the device object to the resulting list of devices
            self.log.write("", show_prefix=False)
            devices_found.append(d)

        return devices_found

    def ping_nmap(self, address: str, timeout: float, tries: int, pingtype=None):
        """Attempts to do various nmap ping strategies to identify if a host is up or
        not. Used by `self.ping()`. Returns True if the host is up, False
        otherwise.
        https://nmap.org/book/host-discovery-techniques.html
        """
        # delegate to the shared `nmap` wrapper. A failure to run/parse nmap is
        # treated as "host not confirmed up" so the sweep loop never crashes.
        try:
            return self.nmap_client.ping_host(address, timeout=timeout,
                                              tries=tries, pingtype=pingtype)
        except NmapError as e:
            self.log.write("nmap ping of %s failed: %s" % (address, e))
            return False

    def ping_classic(self, address: str, timeout=None, tries=None):
        """Pings a given IP address and returns True if the host is up.

        This may attempt multiple pings to reduce inaccuracy or unreturned pings
        due to network latency.
        """
        # establish defaults if none were given
        timeout = self.config.ping_timeout if timeout is None else timeout
        tries = self.config.ping_tries if tries is None else tries

        # try a number of times to ping the ip address
        for i in range(tries):
            # the more times we try, the longer the timeout we'll allow
            timeout = timeout + (i * timeout)

            # spawn a ping process and return the exit code
            args = [
                "ping", address,
                "-c", "1",
                "-t", "8",
                "-W", str(timeout)
            ]
            result = subprocess.run(args,
                                    stdout=subprocess.DEVNULL,
                                    stderr=subprocess.DEVNULL)

            # if we didn't get a zero return value, we'll try again
            if result.returncode != 0:
                continue
            return True
        return False

    def ping(self, address: str, timeout=None, tries=None):
        """Attempts a variety of different pinging techniques to determine if a host
        is up and responding.
        """
        # establish limits and run the nmap helper
        timeout = self.config.ping_timeout if timeout is None else timeout
        tries = self.config.ping_tries if tries is None else tries

        # ATTEMPT 1: Classic 'ping' utility
        if self.ping_classic(address, timeout=timeout, tries=tries):
            return True
        # ATTEMPT 2: nmap default echo request (basically the same as 'ping')
        elif self.ping_nmap(address, timeout, tries):
            return True
        # ATTEMPT 3-N: various nmap ping styles
        else:
            for pt in ["pp", "pm", "ps", "pa", "pu"]:
                if self.ping_nmap(address, timeout, tries, pingtype=pt):
                    return True

        # if we reach here without returning true, we'll assume the host is
        # offline
        return False

    def arp(self, address: str, do_ping=True):
        """Look up the MAC address of the given IP address. If 'do_ping' is True, the
        address will be pinged beforehand (to fill up the ARP cache).
        The MAC address is returned as a string.
        """
        # if specified, ping the address
        if do_ping:
            assert self.ping(address), "the address did not respond to a ping"

        # delegate to the shared `arp` wrapper, which resolves the IP to a MAC
        # address via the system ARP cache. A missing entry yields None; any
        # failure to run/parse `arp` is treated as "not found" so the sweep loop
        # never crashes.
        try:
            return self.arp_client.lookup(address)
        except ArpError as e:
            self.log.write("arp lookup of %s failed: %s" % (address, e))
            return None

    def mac_vendor(self, macaddr: str):
        """Looks up the vendor for a given MAC address. Returns a string."""
        # sanitize the MAC address
        macaddr_sanitized = macaddr.lower().replace("-", ":").replace(".", ":")

        # perform a lookup
        mac = MacLookup()
        return mac.lookup(macaddr_sanitized)

    def mac_vendor_refresh_cache(self):
        """Refreshes the MAC address vendor cache."""
        BaseMacLookup.cache_path = self.config.mac_vendor_cache_path
        mac = MacLookup()
        mac.update_vendors()


# ============================== Service Oracle ============================== #
class WardenOracle(Oracle):
    def init_nla(self):
        """Registers NLA endpoints for network device queries."""
        super().init_nla()
        self.nla_endpoints += [
            NLAEndpoint.from_json({
                "name": "get_network_devices",
                "description": "List devices currently on the network and their "
                               "online status. Phrases like what devices are on "
                               "the network, who's online, who's home, show me "
                               "network devices, is anything connected, etc."
            }).set_handler(nla_get_network_devices),
        ]

    def endpoints(self):
        """Endpoint definition function."""
        super().endpoints()

        # This endpoint returns a list of all configured devices. The response
        # only contains static information that was defined in the configuration
        # file.
        @self.server.route("/known_devices", methods=["GET"])
        def endpoint_known_devices():
            if not flask.g.user:
                return self.make_response(rstatus=404)

            # retrieve all devices and build a JSON dictionary to return
            result = []
            for device in self.service.config.known_devices:
                result.append(device.to_json())
            return self.make_response(payload=result)

        # This endpoint retrieves all devices stored in the warden's cache.
        @self.server.route("/devices", methods=["GET"])
        def endpoint_devices():
            if not flask.g.user:
                return self.make_response(rstatus=404)

            # were tags provided to filter with? If so, only return known
            # devices that have all of the provided tags
            tags = flask.g.jdata.get("tags", None)
            if tags is not None and not isinstance(tags, list):
                return self.make_response(rstatus=400,
                                          rmessage="The \"tags\" field must be a list.")

            # retrieve all devices from the warden's cache and build a JSON
            # dictionary to return.
            result = []
            named_devices_already_added = {}
            for addr in self.service.cache:
                d = self.service.cache[addr]

                # if tags were provided, skip devices that don't have all
                # requested tags
                if tags is not None and d.known_device is not None:
                    has_all_tags = True
                    for t in tags:
                        tag_sanitized = str(t).strip().lower()
                        if tag_sanitized not in d.known_device.tags:
                            has_all_tags = False
                            break
                    if not has_all_tags:
                        continue

                result.append(d.to_json())
            self.log.write("Returning a list of %d connected devices to %s" %
                           (len(result), flask.g.user.config.username))
            return self.make_response(payload=result)


# =============================== NLA Handlers =============================== #
def nla_get_network_devices(oracle, jdata):
    """NLA handler that returns a formatted list of network devices grouped by
    when they were last seen. Devices are sorted into time-based buckets
    (online, recent, older) for readability. Only non-empty buckets are shown,
    and a summary line is included at the top.
    """
    params = NLAEndpointInvokeParameters.from_json(jdata)

    # collect all devices from the warden's cache
    devices = []
    for addr in oracle.service.cache:
        devices.append(oracle.service.cache[addr])

    if len(devices) == 0:
        return NLAResult.from_json({
            "success": True,
            "message": "No devices have been detected on the network yet."
        })

    # sort devices by last_seen descending (most recent first)
    devices.sort(key=lambda d: d.last_seen.timestamp() if d.last_seen else 0,
                 reverse=True)

    # define time buckets (in seconds) — a concise subset for NLA output
    now = datetime.now()
    buckets = [
        {"name": "Currently online",               "time": 120,    "list": []},
        {"name": "Last seen within 15 minutes",     "time": 900,    "list": []},
        {"name": "Last seen within the last hour",  "time": 3600,   "list": []},
        {"name": "Last seen within the last day",   "time": 86400,  "list": []},
        {"name": "Last seen over a day ago",        "time": None,   "list": []},
    ]

    # place each device into the first matching bucket
    for device in devices:
        if device.last_seen is None:
            buckets[-1]["list"].append(device)
            continue
        diff = now.timestamp() - device.last_seen.timestamp()
        placed = False
        for b in buckets:
            if b["time"] is not None and diff <= b["time"]:
                b["list"].append(device)
                placed = True
                break
        if not placed:
            buckets[-1]["list"].append(device)

    # count online devices (first bucket)
    online_count = len(buckets[0]["list"])

    # build the formatted message
    lines = []
    lines.append("Network Devices (%d total, %d currently online):" %
                 (len(devices), online_count))
    lines.append("")

    for b in buckets:
        if len(b["list"]) == 0:
            continue
        lines.append("%s:" % b["name"])
        for device in b["list"]:
            lines.append(_format_device_line(device))
        lines.append("")

    msg = "\n".join(lines).rstrip()

    return NLAResult.from_json({
        "success": True,
        "message": msg,
        "message_context": "This is a summary of devices on the local network. "
                           "Rephrase naturally. Use the device names when available."
    })


def _format_device_line(device):
    """Formats a single device into a readable bullet line for NLA output.

    Uses the known device name if available, otherwise falls back to the MAC
    address with an optional vendor label. The device IP and last-seen time
    are appended when known.
    """
    # determine the display name
    if device.known_device is not None:
        name = device.known_device.name
    elif device.hw_addr is not None:
        name = device.hw_addr.macaddr
        if device.hw_addr.vendor is not None:
            name += " (%s)" % device.hw_addr.vendor
    else:
        name = "Unknown Device"

    # determine the IP address
    ip = ""
    if device.net_addr is not None:
        ip = " - %s" % device.net_addr.ipaddr

    # determine the last-seen time
    seen = ""
    if device.last_seen is not None:
        seen = " - last seen %s" % device.last_seen.strftime("%I:%M:%S %p")

    return "· %s%s%s" % (name, ip, seen)


# =============================== Runner Code ================================ #
if __name__ == "__main__":
    cli = ServiceCLI(config=WardenConfig, service=WardenService, oracle=WardenOracle)
    cli.run()

